export { default as Header } from "./header";
export { default as Profile } from "./profile";
export { default as About } from "./about";
export { default as Languages } from "./languages";
export { default as Tabs } from "./tabs";
export { default as More } from "./more";
export { default as Projects } from "./projects";
export { default as Button } from "./button";
export { default as Footer } from "./footer";
